// Main Sidebarlinks

import { BotMessageSquare, File, Home, Layout, LineChart } from "lucide-react";

export const Sidebarlinks = [
  {
    icons: Home,
    route: "/dashboard",
    titel: "Dashboard",
  },
  {
    icons: Layout,
    route: "/resume-template",
    titel: "Template",
  },
  {
    icons: File,
    route: "/my-resume",
    titel: "My Resume",
  },
  {
    icons: BotMessageSquare,
    route: "/genrate-ai",
    titel: "AI Genrated",
  },
  {
    icons: LineChart,
    route: "/ats-checker",
    titel: "ATS Checker",
  },
];

// Resume select domain filed options
export const industries = [
  { label: "Accounting", value: "accounting" },
  { label: "Airlines", value: "airlines" },
  {
    label: "Alternative Dispute Resolution",
    value: "alternative dispute resolution",
  },
  { label: "Alternative Medicine", value: "alternative medicine" },
  { label: "Animation", value: "animation" },
  { label: "Apparel & Fashion", value: "apparel & fashion" },
  { label: "Architecture", value: "architecture" },
  { label: "Arts", value: "arts" },
  { label: "Crafts", value: "crafts" },
  { label: "Automotive", value: "automotive" },
  { label: "Aviation", value: "aviation" },
  { label: "Aerospace", value: "aerospace" },
  { label: "Banking", value: "banking" },
  { label: "Biotechnology", value: "biotechnology" },
  { label: "Broadcast Media", value: "broadcast media" },
  { label: "Building Materials", value: "building materials" },
  {
    label: "Business Supplies & Equipment",
    value: "business supplies & equipment",
  },
  { label: "Capital Markets", value: "capital markets" },
  { label: "Chemicals", value: "chemicals" },
  { label: "Social Organization", value: "social organization" },
  { label: "Civil Engineering", value: "civil engineering" },
  { label: "Network Security", value: "network security" },
  { label: "Games Development", value: "games development" },
  { label: "Hardware Engineering", value: "hardware engineering" },
  { label: "Network Engineering", value: "network engineering" },
  { label: "Software Development", value: "software development" },
  { label: "Construction", value: "construction" },
  { label: "Consumer Electronics", value: "consumer electronics" },
  { label: "Consumer Goods", value: "consumer goods" },
  { label: "Consumer Services", value: "consumer services" },
  { label: "Cosmetics", value: "cosmetics" },
  { label: "Dairy", value: "dairy" },
  { label: "Defense & Space", value: "defense & space" },
  { label: "Design", value: "design" },
  { label: "Education Management", value: "education management" },
  { label: "Electronic Manufacturing", value: "electronic manufacturing" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Environment", value: "environment" },
  { label: "Events", value: "events" },
  { label: "Executive Office", value: "executive office" },
  { label: "Facilities Services", value: "facilities services" },
  { label: "Agricultural", value: "agricultural" },
  { label: "Financial Services", value: "financial services" },
  { label: "Fine Art", value: "fine art" },
  { label: "Harvest", value: "harvest" },
  { label: "Food & Beverages", value: "food & beverages" },
  { label: "Food Production", value: "food production" },
  { label: "Fundraising", value: "fundraising" },
  { label: "Furniture", value: "furniture" },
  { label: "Government Administration", value: "government administration" },
  { label: "Government Relations", value: "government relations" },
  { label: "Graphic Design", value: "graphic design" },
  { label: "Health", value: "health" },
  { label: "Wellness", value: "wellness" },
  { label: "Fitness", value: "fitness" },
  { label: "Education", value: "education" },
  { label: "Health Care", value: "health care" },
  { label: "Hospital", value: "hospital" },
  { label: "Hospitality", value: "hospitality" },
  { label: "Human Resources", value: "human resources" },
  { label: "Import & Export", value: "import & export" },
  { label: "Individual Services", value: "individual services" },
  { label: "Family Services", value: "family services" },
  { label: "Industrial Automation", value: "industrial automation" },
  { label: "Information Services", value: "information services" },
  {
    label: "Information Technology & Services",
    value: "information technology & services",
  },
  { label: "Insurance", value: "insurance" },
  { label: "International Affairs", value: "international affairs" },
  {
    label: "International Trade & Development",
    value: "international trade & development",
  },
  { label: "Internet", value: "internet" },
  { label: "Investment Banking", value: "investment banking" },
  { label: "Investment Management", value: "investment management" },
  { label: "Justice", value: "justice" },
  { label: "Law Enforcement", value: "law enforcement" },
  { label: "Law Practice", value: "law practice" },
  { label: "Legal Services", value: "legal services" },
  { label: "Legislative Office", value: "legislative office" },
  { label: "Travel & Tourism", value: "travel & tourism" },
  { label: "Logistics", value: "logistics" },
  { label: "Supply Chain", value: "supply chain" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Luxury Goods", value: "luxury goods" },
  { label: "Machinery", value: "machinery" },
  { label: "Management Consulting", value: "management consulting" },
  { label: "Market Research", value: "market research" },
  { label: "Marketing", value: "marketing" },
  { label: "Advertising", value: "advertising" },
  { label: "Mechanical", value: "mechanical" },
  { label: "Industrial Engineering", value: "industrial engineering" },
  { label: "Medical Devices", value: "medical devices" },
  { label: "Medical Practice", value: "medical practice" },
  { label: "Mental Health Care", value: "mental health care" },
  { label: "Military", value: "military" },
  { label: "Mining & Metals", value: "mining & metals" },
  { label: "Motion Pictures & Film", value: "motion pictures & film" },
  { label: "Museums", value: "museums" },
  { label: "Institutions", value: "institutions" },
  { label: "Music", value: "music" },
  { label: "Nanotechnology", value: "nanotechnology" },
  { label: "Newspapers", value: "newspapers" },
  {
    label: "Non Profit Organization Management",
    value: "non profit organization management",
  },
  { label: "Oil", value: "oil" },
  { label: "Energy", value: "energy" },
  { label: "Online Media", value: "online media" },
  { label: "Fulfillment", value: "fulfillment" },
  { label: "Freight Delivery", value: "freight delivery" },
  { label: "Packaging & Containers", value: "packaging & containers" },
  { label: "Paper", value: "paper" },
  { label: "Forest", value: "forest" },
  { label: "Pharmaceuticals", value: "pharmaceuticals" },
  { label: "Photography", value: "photography" },
  { label: "Plastics", value: "plastics" },
  { label: "Political Organization", value: "political organization" },
  { label: "Printing", value: "printing" },
  { label: "Professional Training", value: "professional training" },
  { label: "Coaching", value: "coaching" },
  { label: "Program Development", value: "program development" },
  { label: "Public Policy", value: "public policy" },
  { label: "Public Relations", value: "public relations" },
  { label: "Communications", value: "communications" },
  { label: "Public Safety", value: "public safety" },
];
// Resume select experience filed options
export const experience = [
  {
    label: "Internship",
    value: "internship",
  },
  {
    label: "Entry level",
    value: "entry level",
  },
  {
    label: "Associate",
    value: "associate",
  },
  {
    label: "Junior level",
    value: "junior level",
  },
  {
    label: "Mid-Senior level",
    value: "mid senior level",
  },
  {
    label: "Director",
    value: "director",
  },
  {
    label: "Executive",
    value: "executive",
  },
];

export const TopNavoptionLink = [
  {
    title: "CONTACT",
    href: "contact",
  },
  {
    title: "EXPERIENCE",
    href: "experience",
  },
  {
    title: "PROJECT",
    href: "project",
  },
  {
    title: "EDUCATION",
    href: "education",
  },
  {
    title: "CERTIFICATIONS",
    href: "certipications",
  },
  {
    title: "COURSE",
    href: "coures",
  },
  {
    title: "SKILLS",
    href: "skills",
  },
  {
    title: "Description",
    href: "description",
  },
  {
    title: "PREVIEW",
    href: "preview",
  },
];
export const contrary = [
  { name: "Afghanistan", value: "Afghanistan" },
  { name: "Albania", value: "Albania" },
  { name: "Algeria", value: "Algeria" },
  { name: "Andorra", value: "Andorra" },
  { name: "Angola", value: "Angola" },
  { name: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { name: "Argentina", value: "Argentina" },
  { name: "Armenia", value: "Armenia" },
  { name: "Australia", value: "Australia" },
  { name: "Austria", value: "Austria" },
  { name: "Azerbaijan", value: "Azerbaijan" },
  { name: "Bahamas", value: "Bahamas" },
  { name: "Bahrain", value: "Bahrain" },
  { name: "Bangladesh", value: "Bangladesh" },
  { name: "Barbados", value: "Barbados" },
  { name: "Belarus", value: "Belarus" },
  { name: "Belgium", value: "Belgium" },
  { name: "Belize", value: "Belize" },
  { name: "Benin", value: "Benin" },
  { name: "Bhutan", value: "Bhutan" },
  { name: "Bolivia", value: "Bolivia" },
  { name: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { name: "Botswana", value: "Botswana" },
  { name: "Brazil", value: "Brazil" },
  { name: "Brunei Darussalam", value: "Brunei Darussalam" },
  { name: "Bulgaria", value: "Bulgaria" },
  { name: "Burkina Faso", value: "Burkina Faso" },
  { name: "Burundi", value: "Burundi" },
  { name: "Cambodia", value: "Cambodia" },
  { name: "Cameroon", value: "Cameroon" },
  { name: "Canada", value: "Canada" },
  { name: "Cape Verde", value: "Cape Verde" },
  { name: "Central African Republic", value: "Central African Republic" },
  { name: "Chad", value: "Chad" },
  { name: "Chile", value: "Chile" },
  { name: "China", value: "China" },
  { name: "Colombia", value: "Colombia" },
  { name: "Comoros", value: "Comoros" },
  { name: "Congo (Republic of the)", value: "Congo (Republic of the)" },
  { name: "Costa Rica", value: "Costa Rica" },
  { name: "Côte d’Ivoire", value: "Côte d’Ivoire" },
  { name: "Croatia", value: "Croatia" },
  { name: "Cuba", value: "Cuba" },
  { name: "Cyprus", value: "Cyprus" },
  { name: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
  {
    name: "Democratic People’s Republic of Korea",
    value: "Democratic People’s Republic of Korea",
  },
  {
    name: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  { name: "Denmark", value: "Denmark" },
  { name: "Djibouti", value: "Djibouti" },
  { name: "Dominica", value: "Dominica" },
  { name: "Dominican Republic", value: "Dominican Republic" },
  { name: "Ecuador", value: "Ecuador" },
  { name: "Egypt", value: "Egypt" },
  { name: "El Salvador", value: "El Salvador" },
  { name: "Equatorial Guinea", value: "Equatorial Guinea" },
  { name: "Eritrea", value: "Eritrea" },
  { name: "Estonia", value: "Estonia" },
  { name: "Ethiopia", value: "Ethiopia" },
  { name: "Fiji", value: "Fiji" },
  { name: "Finland", value: "Finland" },
  { name: "France", value: "France" },
  { name: "Gabon", value: "Gabon" },
  { name: "Gambia", value: "Gambia" },
  { name: "Georgia", value: "Georgia" },
  { name: "Germany", value: "Germany" },
  { name: "Ghana", value: "Ghana" },
  { name: "Greece", value: "Greece" },
  { name: "Grenada", value: "Grenada" },
  { name: "Guatemala", value: "Guatemala" },
  { name: "Guinea", value: "Guinea" },
  { name: "Guinea-Bissau", value: "Guinea-Bissau" },
  { name: "Guyana", value: "Guyana" },
  { name: "Haiti", value: "Haiti" },
  { name: "Honduras", value: "Honduras" },
  { name: "Hungary", value: "Hungary" },
  { name: "Iceland", value: "Iceland" },
  { name: "India", value: "India" },
  { name: "Indonesia", value: "Indonesia" },
  { name: "Iran", value: "Iran" },
  { name: "Iraq", value: "Iraq" },
  { name: "Ireland", value: "Ireland" },
  { name: "Israel", value: "Israel" },
  { name: "Italy", value: "Italy" },
  { name: "Jamaica", value: "Jamaica" },
  { name: "Japan", value: "Japan" },
  { name: "Jordan", value: "Jordan" },
  { name: "Kazakhstan", value: "Kazakhstan" },
  { name: "Kenya", value: "Kenya" },
  { name: "Kiribati", value: "Kiribati" },
  { name: "Kuwait", value: "Kuwait" },
  { name: "Kyrgyzstan", value: "Kyrgyzstan" },
  {
    name: "Lao People’s Democratic Republic",
    value: "Lao People’s Democratic Republic",
  },
  { name: "Latvia", value: "Latvia" },
  { name: "Lebanon", value: "Lebanon" },
  { name: "Lesotho", value: "Lesotho" },
  { name: "Liberia", value: "Liberia" },
  { name: "Libya", value: "Libya" },
  { name: "Liechtenstein", value: "Liechtenstein" },
  { name: "Lithuania", value: "Lithuania" },
  { name: "Luxembourg", value: "Luxembourg" },
  { name: "Madagascar", value: "Madagascar" },
  { name: "Malawi", value: "Malawi" },
  { name: "Malaysia", value: "Malaysia" },
  { name: "Maldives", value: "Maldives" },
  { name: "Mali", value: "Mali" },
  { name: "Malta", value: "Malta" },
  { name: "Marshall Islands", value: "Marshall Islands" },
  { name: "Mauritania", value: "Mauritania" },
  { name: "Mauritius", value: "Mauritius" },
  { name: "Mexico", value: "Mexico" },
  {
    name: "Micronesia (Federated States of)",
    value: "Micronesia (Federated States of)",
  },
  { name: "Monaco", value: "Monaco" },
  { name: "Mongolia", value: "Mongolia" },
  { name: "Montenegro", value: "Montenegro" },
  { name: "Morocco", value: "Morocco" },
  { name: "Mozambique", value: "Mozambique" },
  { name: "Myanmar", value: "Myanmar" },
  { name: "Namibia", value: "Namibia" },
  { name: "Nauru", value: "Nauru" },
  { name: "Nepal", value: "Nepal" },
  { name: "Netherlands", value: "Netherlands" },
  { name: "New Zealand", value: "New Zealand" },
  { name: "Nicaragua", value: "Nicaragua" },
  { name: "Niger", value: "Niger" },
  { name: "Nigeria", value: "Nigeria" },
  { name: "Norway", value: "Norway" },
  { name: "Oman", value: "Oman" },
  { name: "Pakistan", value: "Pakistan" },
  { name: "Palau", value: "Palau" },
  { name: "Panama", value: "Panama" },
  { name: "Papua New Guinea", value: "Papua New Guinea" },
  { name: "Paraguay", value: "Paraguay" },
  { name: "Peru", value: "Peru" },
  { name: "Philippines", value: "Philippines" },
  { name: "Poland", value: "Poland" },
  { name: "Portugal", value: "Portugal" },
  { name: "Qatar", value: "Qatar" },
  { name: "Republic of Korea", value: "Republic of Korea" },
  { name: "Republic of Moldova", value: "Republic of Moldova" },
  { name: "Romania", value: "Romania" },
  { name: "Russian Federation", value: "Russian Federation" },
  { name: "Rwanda", value: "Rwanda" },
  { name: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { name: "Saint Lucia", value: "Saint Lucia" },
  {
    name: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { name: "Samoa", value: "Samoa" },
  { name: "San Marino", value: "San Marino" },
  { name: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { name: "Saudi Arabia", value: "Saudi Arabia" },
  { name: "Senegal", value: "Senegal" },
  { name: "Serbia", value: "Serbia" },
  { name: "Seychelles", value: "Seychelles" },
  { name: "Sierra Leone", value: "Sierra Leone" },
  { name: "Singapore", value: "Singapore" },
  { name: "Slovakia", value: "Slovakia" },
  { name: "Slovenia", value: "Slovenia" },
  { name: "Solomon Islands", value: "Solomon Islands" },
  { name: "Somalia", value: "Somalia" },
  { name: "South Africa", value: "South Africa" },
  { name: "South Sudan", value: "South Sudan" },
  { name: "Spain", value: "Spain" },
  { name: "Sri Lanka", value: "Sri Lanka" },
  { name: "Sudan", value: "Sudan" },
  { name: "Suriname", value: "Suriname" },
  { name: "Swaziland", value: "Swaziland" },
  { name: "Switzerland", value: "Switzerland" },
  { name: "Sweden", value: "Sweden" },
  { name: "Syria", value: "Syria" },
  { name: "Tajikistan", value: "Tajikistan" },
  { name: "Thailand", value: "Thailand" },
  {
    name: "The former Yugoslav Republic of Macedonia",
    value: "The former Yugoslav Republic of Macedonia",
  },
  { name: "Timor Leste", value: "Timor Leste" },
  { name: "Togo", value: "Togo" },
  { name: "Tonga", value: "Tonga" },
  { name: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { name: "Tunisia", value: "Tunisia" },
  { name: "Turkey", value: "Turkey" },
  { name: "Turkmenistan", value: "Turkmenistan" },
  { name: "Tuvalu", value: "Tuvalu" },
  { name: "Uganda", value: "Uganda" },
  { name: "Ukraine", value: "Ukraine" },
  { name: "United Arab Emirates", value: "United Arab Emirates" },
  { name: "United Kingdom", value: "United Kingdom" },
  { name: "United Republic of Tanzania", value: "United Republic of Tanzania" },
  { name: "United States", value: "United States" },
  { name: "Uruguay", value: "Uruguay" },
  { name: "Uzbekistan", value: "Uzbekistan" },
  { name: "Vanuatu", value: "Vanuatu" },
  { name: "Venezuela", value: "Venezuela" },
  { name: "Vietnam", value: "Vietnam" },
  { name: "Yemen", value: "Yemen" },
  { name: "Zambia", value: "Zambia" },
  { name: "Zimbabwe", value: "Zimbabwe" },
];

export const MAX_FREE_COUNT = 5;

export interface Education {
  id: number;
  universityName: string;
  startDate: string;
  endDate: string;
  degree: string;
  major: string;
  description: string;
}
export interface Experience {
  id: number;
  title: string;
  companyName: string;
  city: string;
  state: string;
  startDate: string;
  endDate: string;
  currentlyWorking: boolean;
  workSummery: string;
}

export interface Skill {
  id: number;
  name: string;
  rating: number;
}

export interface ResumeProps {
  firstName: string;
  lastName: string;
  jobTitle: string;
  address: string;
  phone: string;
  email: string;
  themeColor: string;
  summery: string;
  experience: Experience[];
  education: Education[];
  skills: Skill[];
}
